apiVersion: 1

# export command: 
# mkdir -p data_sources && curl -s "http://localhost:3000/api/datasources"  -u saarsec:...|jq -c -M '.[]'|split -l 1 - data_sources/

datasources:
  - "id": 1
    "orgId": 1
    "name": "CTF DB"
    "uid": "DS_CTF_DB"
    "type": "postgres"
    "typeLogoUrl": "public/app/plugins/datasource/postgres/img/postgresql_logo.svg"
    "access": "proxy"
    "url": "localhost"
    "user": "{{ pg_username }}"
    "database": "saarctf"
    "basicAuth": false
    "isDefault": true
    "jsonData":
      "postgresVersion": 1200
      "sslmode": "disable"
    "secureJsonData":
      "password": "{{ pg_password }}"
    "readOnly": false

  - "id": 2
    "orgId": 1
    "name": "Prometheus"
    "uid": "DS_PROMETHEUS"
    "type": "prometheus"
    "typeLogoUrl": "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
    "access": "proxy"
    "url": "http://localhost:9090"
    "password": ""
    "user": ""
    "database": ""
    "basicAuth": false
    "isDefault": false
    "jsonData":
      "httpMethod": "GET"
      "keepCookies": []
    "readOnly": false

  - "id": 3
    "orgId": 1
    "name": "Metrics DB"
    "uid": "DS_METRICS_DB"
    "type": "postgres"
    "typeLogoUrl": "public/app/plugins/datasource/postgres/img/postgresql_logo.svg"
    "access": "proxy"
    "url": "localhost"
    "user": "{{ pg_username }}"
    "database": "saarctf_metrics"
    "basicAuth": false
    "isDefault": false
    "jsonData":
      "postgresVersion": 1500
      "timescaledb": true
      "sslmode": "disable"
    "secureJsonData":
      "password": "{{ pg_password }}"
    "readOnly": false
