# Used to set facts from gameserver configs in ansible playbooks
#
# To set multiple facts use like so:
#
#  - name: Set configuration facts from gameserver conf
#    vars:
#      fact_to_config:
#        influx_server: "databases postgres server"
#         ...
#    include_tasks: ../fact_from_gameserver_conf.yml
#    loop: "{{ fact_to_config | dict2items }}"
#
# If you only need a single fact, you can do this:
#
#  - name: Set configuration facts from gameserver conf
#    vars:
#      item:
#        key: influx_server
#        value: "database postgres server"
#    include_tasks: ../fact_from_gameserver_conf.yml
#
---
- name: Run get command
  ansible.builtin.command:
    cmd: 'gspython /opt/gameserver/saarctf_commons/config.py get {{ item.value }}'
  register: get_output

- name: Set fact based on stdout
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ get_output.stdout }}"

- name: Showfact
  debug:
    msg: "fact: {{ item.value }}; value: {{ get_output.stdout }}"