{
 "title": "Alerts",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Alert Status", "type": "alertlist", "gridPos": { "h": 24, "w": 6, "x": 0, "y": 0 } },
  {
   "title": "Server RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{} * 100) / node_memory_MemTotal_bytes{})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server pcap Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/pcaps\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/mnt/pcaps\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}} ({{device}} @ \"{{mountpoint}}\")"
    }
   ]
  },
  {
   "title": "Flag Submitter Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  100 * AVG(fd_count) / AVG(fd_max) AS \"File Descriptor Usage\"\nFROM submitter_connections \nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Conntrack Entries Limit",
   "type": "timeseries",
   "description": ":= current conntrack entries  /  conntrack entry limit",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  100 * AVG(ip_conntrack_count) / AVG(ip_conntrack_max) AS \"Conntrack Usage\"\nFROM conntrack \nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NOP Team Ping Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  MAX(maximum_response_ms) AS \"max. response time\"\nFROM ping \nWHERE $__timeFilter(time) AND url = '10.32.1.2'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NOP Team Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  MAX(percent_packet_loss) AS \"packet loss\"\nFROM ping \nWHERE $__timeFilter(time) AND url = '10.32.1.2'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hetzner API Rate Limits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  last(remaining) AS \"Remaining API Requests\"\nFROM hetzner_rates \nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}