{
 "title": "Idiots doing traffic analysis",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "Host",
    "query": "SELECT DISTINCT \"host\" FROM system"
   }
  ]
 },
 "panels": [
  {
   "title": "Vulnbox send / receive",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), interface, AVG(sent) AS sent, AVG(recv) AS recv\nFROM (\n  SELECT time,\n    interface,\n    (AVG(bytes_recv) - LAG(AVG(bytes_recv), 1) OVER (ORDER BY 2, 1)) * -8 / extract('epoch' from (time - LAG(time, 1) OVER (ORDER BY 2, 1))) AS sent,\n    (AVG(bytes_sent) - LAG(AVG(bytes_sent), 1) OVER (ORDER BY 2, 1)) * 8 / extract('epoch' from (time - LAG(time, 1) OVER (ORDER BY 2, 1))) AS recv\n  FROM net \n  WHERE $__timeFilter(time) AND \"host\" = 'vpn' AND interface LIKE 'tun%'\n  GROUP BY interface, time\n  ORDER BY 2, 1\n)\nGROUP BY 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  \"host\", \n  AVG(used_percent) AS \"mem.mean\"\nFROM mem\nWHERE $__timeFilter(time)\nGROUP BY 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total system load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  \"host\",\n  AVG(usage_idle) * -1 + 100 AS total,\n  AVG(usage_user) AS \"user\",\n  AVG(usage_system) AS \"system\"\nFROM cpu\nWHERE $__timeFilter(time)\nGROUP BY 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Traffic Of router peers",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT public_key,\n  MAX(tx_bytes) AS \"TX\", \n  MAX(rx_bytes) AS \"RX\"\nFROM wireguard_peer\nWHERE $__timeFilter(time) AND \"host\" = 'vpn'\nGROUP BY 1\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "$HOST",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "HOST",
   "collapsed": true,
   "panels": [
    {
     "title": "Interface loads (not wireguard)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "rawSql": "SELECT $__timeGroupAlias(time, $__interval), interface, AVG(sent) AS sent, AVG(recv) AS recv\nFROM (\n  SELECT time,\n    interface,\n    (AVG(bytes_sent) - LAG(AVG(bytes_sent), 1) OVER (ORDER BY 2, 1)) * 8 / extract('epoch' from (time - LAG(time, 1) OVER (ORDER BY 2, 1))) AS sent,\n    (AVG(bytes_recv) - LAG(AVG(bytes_recv), 1) OVER (ORDER BY 2, 1)) * -8 / extract('epoch' from (time - LAG(time, 1) OVER (ORDER BY 2, 1))) AS recv\n  FROM net \n  WHERE $__timeFilter(time) AND \"host\" IN ($HOST) AND NOT (interface LIKE 'tun%' OR interface LIKE 'veth%' OR interface LIKE 'br%' OR interface LIKE 'docker%')\n  GROUP BY interface, time\n  ORDER BY 2, 1\n)\nGROUP BY 1, 2\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}