{
 "title": "Hetzner Cloud Vulnboxes",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cloud Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloud_servers",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "servers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "ALL" ], "type": "alias" }
      ],
      [
       { "params": [ "RUNNING" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "running" ], "type": "alias" }
      ],
      [
       { "params": [ "BUSY" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "busy" ], "type": "alias" }
      ],
      [
       { "params": [ "CREATING" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "creating" ], "type": "alias" }
      ],
      [
       { "params": [ "BOOTING" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "booting" ], "type": "alias" }
      ],
      [
       { "params": [ "STOPPED" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "stopped" ], "type": "alias" }
      ],
      [
       { "params": [ "MISSING" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "deleting" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Servers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col @$tag_backend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "backend" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloud_servers",
     "query": "SELECT max(\"servers\") AS \"servers\", max(\"BUSY\")+max(\"CREATING\")+max(\"MISSING\")+max(\"BOOTING\")+max(\"STOPPED\") AS \"not running\" FROM \"cloud_servers\" WHERE $timeFilter GROUP BY time($__interval), \"backend\" fill(null)",
     "select": [
      [
       { "params": [ "servers" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "servers" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hetzner API Rate Limits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hetzner_rates",
     "select": [
      [
       { "params": [ "remaining" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "remaining" ], "type": "alias" }
      ],
      [
       { "params": [ "limit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vulnbox CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col @$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vulnboxes",
     "query": "SELECT mean(\"cpu\") FROM \"vulnboxes\" WHERE $timeFilter GROUP BY time($__interval), \"server\" fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cpu" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vulnbox Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$col @$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vulnboxes",
     "query": "SELECT mean(\"network.0.bandwidth.in\")+mean(\"network.0.bandwidth.out\") AS \"bandwidth\" FROM \"vulnboxes\" WHERE $timeFilter GROUP BY time($__interval), \"server\" fill(null)",
     "select": [
      [
       { "params": [ "network.0.bandwidth.in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "repeat": "Server",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vulnboxes",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}