{
 "title": "Flag Submitter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "team",
    "query": "SHOW TAG VALUES FROM \"submitter_flags\" WITH KEY = \"team\""
   }
  ]
 },
 "panels": [
  {
   "title": "Submitted Flags",
   "type": "timeseries",
   "description": "Submitted flags per minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "submitter_flags",
     "query": "SELECT mean(\"count_new\") *4 AS \"new\", mean(\"count_old\") *4 AS \"old\", mean(\"count_expired\") *4 AS \"expired\", mean(\"count_invalid\") *4 AS \"invalid\", mean(\"count_nop\") *4 AS \"nop\", mean(\"count_own\") *4 AS \"own\" FROM \"submitter_flags\" WHERE (\"team\" =~ /^$team$/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "count_new" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "new" ], "type": "alias" }
      ],
      [
       { "params": [ "count_old" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "old" ], "type": "alias" }
      ],
      [
       { "params": [ "count_expired" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "expired" ], "type": "alias" }
      ],
      [
       { "params": [ "count_invalid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "invalid" ], "type": "alias" }
      ],
      [
       { "params": [ "count_nop" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "nop" ], "type": "alias" }
      ],
      [
       { "params": [ "count_own" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "own" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "team", "operator": "=~", "value": "/^$team$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Flags Incoming",
   "type": "timeseries",
   "description": "How many flags we receive per second",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "flags",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "submitter_flags",
     "query": "SELECT (sum(\"count_new\") + sum(\"count_old\") + sum(\"count_expired\") + sum(\"count_invalid\") + sum(\"count_own\") + sum(\"count_nop\")) * 1000  / $__interval_ms \nFROM \"submitter_flags\" WHERE (\"team\" =~ /^$team$/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "count_expired" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Valid Flags",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "valid flags",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "submitter_flags",
     "select": [
      [
       { "params": [ "count_new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "team", "operator": "=~", "value": "/^$team$/" }
     ]
    }
   ]
  },
  {
   "title": "Flag Submitter Connections",
   "type": "timeseries",
   "description": "All connections / fd's, ignoring the \"team\" filter",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "submitter_connections",
     "select": [
      [
       { "params": [ "open_connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "open connections" ], "type": "alias" }
      ],
      [
       { "params": [ "total_connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 15" ], "type": "math" },
       { "params": [ "connections per second" ], "type": "alias" }
      ],
      [
       { "params": [ "fd_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "fd count" ], "type": "alias" }
      ],
      [
       { "params": [ "fd_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "fd limit" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flag Submitter Cache Performance",
   "type": "timeseries",
   "description": "Submission server cache performance for the whole instance, not affected by team filter",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "submitter_cache",
     "select": [
      [
       { "params": [ "cache_hits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cache hits" ], "type": "alias" }
      ],
      [
       { "params": [ "cache_misses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cache misses" ], "type": "alias" }
      ],
      [
       { "params": [ "cache_fails" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cache fails" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Submitted Flags",
   "type": "timeseries",
   "description": "Submitted flags per minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "submitter_flags",
     "query": "SELECT mean(\"count_new\") *4 AS \"new\", mean(\"count_old\") *4 AS \"old\", mean(\"count_expired\") *4 AS \"expired\", mean(\"count_invalid\") *4 AS \"invalid\", mean(\"count_nop\") *4 AS \"nop\", mean(\"count_own\") *4 AS \"own\" FROM \"submitter_flags\" WHERE (\"team\" =~ /^$team$/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "count_new" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "new" ], "type": "alias" }
      ],
      [
       { "params": [ "count_old" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "old" ], "type": "alias" }
      ],
      [
       { "params": [ "count_expired" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "expired" ], "type": "alias" }
      ],
      [
       { "params": [ "count_invalid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "invalid" ], "type": "alias" }
      ],
      [
       { "params": [ "count_nop" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "nop" ], "type": "alias" }
      ],
      [
       { "params": [ "count_own" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4" ], "type": "math" },
       { "params": [ "own" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "team", "operator": "=~", "value": "/^$team$/" }
     ]
    }
   ]
  }
 ]
}