{
 "title": "Alerts",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Alert Status", "type": "alertlist", "gridPos": { "h": 24, "w": 6, "x": 0, "y": 0 } },
  {
   "title": "Server RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{} * 100) / node_memory_MemTotal_bytes{})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server pcap Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/pcaps\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/mnt/pcaps\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}} ({{device}} @ \"{{mountpoint}}\")"
    }
   ]
  },
  {
   "title": "Flag Submitter Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "File Descriptor Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "submitter_connections",
     "query": "SELECT 100 * mean(\"fd_count\") / mean(\"fd_max\") FROM \"submitter_connections\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "fd_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "fd count" ], "type": "alias" }
      ],
      [
       { "params": [ "fd_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "fd limit" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conntrack Entries Limit",
   "type": "graph",
   "description": ":= current conntrack entries  /  conntrack entry limit",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Conntrack Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conntrack",
     "query": "SELECT 100 * mean(\"ip_conntrack_count\") / mean(\"ip_conntrack_max\") \nFROM \"conntrack\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ip_conntrack_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "conntrack entry count" ], "type": "alias" }
      ],
      [
       { "params": [ "ip_conntrack_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "conntrack entries limit" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NOP Team Ping Timing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max. response time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.32.1.1" }
     ]
    }
   ]
  },
  {
   "title": "NOP Team Packet Loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "packet loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.32.1.1" }
     ]
    }
   ]
  },
  {
   "title": "Hetzner API Rate Limits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Remaining API Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hetzner_rates",
     "select": [
      [
       { "params": [ "remaining" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "remaining" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}