{
 "title": "Connection Dashboard",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Traffic - Top Teams",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "src" ], "type": "tag" }
     ],
     "measurement": "traffic",
     "query": "SELECT sum(\"src_bytes\") + sum(\"dst_bytes\") FROM \"traffic\" GROUP BY \"src\"",
     "select": [
      [
       { "params": [ "src_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "total traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "query": "SELECT (sum(\"src_bytes\") + sum(\"dst_bytes\")) * 1000 / $__interval_ms FROM \"traffic\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "src_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "dst_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "total packets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (sum(\"src_packets\") + sum(\"dst_packets\")) * 1000 / $__interval_ms FROM \"traffic\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connection Timing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "query": "SELECT sum(\"connection_times\")/sum(\"connection_count\") AS \"average connection time\", sum(\"connection_count\")*1000/$__interval_ms AS \"connection count\" \nFROM \"traffic\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "connection_times" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth per Team",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_src",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "src" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "query": "SELECT (sum(\"src_bytes\") + sum(\"dst_bytes\")) * 1000 / $__interval_ms FROM \"traffic\" WHERE $timeFilter GROUP BY time($__interval), \"src\" fill(null)",
     "select": [
      [
       { "params": [ "src_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic per Port (last 15min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_proto:$tag_port",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "proto" ], "type": "tag" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "query": "SELECT (sum(\"src_bytes\") + sum(\"dst_bytes\")) / 900 FROM \"traffic\" WHERE $timeFilter GROUP BY time(15m), \"proto\", \"port\" fill(null)",
     "select": [
      [
       { "params": [ "src_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NOP Team Ping",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max. response time" ], "type": "alias" }
      ],
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "packet loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.32.1.1" }
     ]
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "# connections" }
   ],
   "targets": [
    {
     "alias": "open connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "select": [
      [
       { "params": [ "open_connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conntrack Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conntrack",
     "select": [
      [
       { "params": [ "ip_conntrack_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "conntrack entry count" ], "type": "alias" }
      ],
      [
       { "params": [ "ip_conntrack_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "conntrack entries limit" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}