{
 "title": "Traffic Connections (psql)",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(src_bytes+dst_bytes) / ($__interval_ms / 1000) AS \"total traffic\",\n  sum(src_packets+dst_packets) / ($__interval_ms / 1000) AS \"total packets\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Connection Timing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(connection_times) / GREATEST(1, sum(connection_count)) AS \"average connection time\",\n  sum(connection_times) / ($__interval_ms / 1000) AS \"connection count\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Traffic - Top Teams",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  src AS \"src team\",\n  (sum(src_bytes) + sum(dst_bytes)) AS \"total traffic\"\nFROM vpn_traffic\nGROUP BY src\nORDER BY \"total traffic\" DESC"
    }
   ]
  },
  {
   "title": "Bandwidth per Team",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  src,\n  sum(src_bytes + dst_bytes) / ($__interval_ms / 1000) AS \"traffic\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY \"time\", src\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Traffic per port (within timerange)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  max(time) AS \"time\",\n  CONCAT(proto, ' ', CASE WHEN port = -1 THEN '(other)' ELSE CONCAT(':', port) END) AS \"title\",\n  sum(src_bytes + dst_bytes) AS \"bytes\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY proto, port\nORDER BY time, proto, port"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "# connections" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(open_connections) / count(DISTINCT \"time\") AS \"open connections\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY \"time\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NOP Team Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max. response time" ], "type": "alias" }
      ],
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "packet loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.32.1.1" }
     ]
    }
   ]
  },
  {
   "title": "Conntrack Entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conntrack",
     "select": [
      [
       { "params": [ "ip_conntrack_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "conntrack entry count" ], "type": "alias" }
      ],
      [
       { "params": [ "ip_conntrack_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "conntrack entries limit" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}