apiVersion: 1

# export command: 
# mkdir -p data_sources && curl -s "http://localhost:3000/api/datasources"  -u saarsec:...|jq -c -M '.[]'|split -l 1 - data_sources/

datasources:
  - "id": 1
    "orgId": 1
    "name": "CTF DB"
    "type": "postgres"
    "typeLogoUrl": "public/app/plugins/datasource/postgres/img/postgresql_logo.svg"
    "access": "proxy"
    "url": "localhost"
    "user": "PG_USERNAME"
    "password": "PG_PASSWORD"
    "database": "saarctf"
    "basicAuth": false
    "isDefault": true
    "jsonData":
      "postgresVersion": 1000
      "sslmode": "disable"
    "readOnly": false

  - "id": 2
    "orgId": 1
    "name": "Prometheus"
    "type": "prometheus"
    "typeLogoUrl": "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
    "access": "proxy"
    "url": "http://localhost:9090"
    "password": ""
    "user": ""
    "database": ""
    "basicAuth": false
    "isDefault": false
    "jsonData":
      "httpMethod": "GET"
      "keepCookies": []
    "readOnly": false

  - "id": 3
    "orgId": 1
    "name": "InfluxDB"
    "type": "influxdb"
    "typeLogoUrl": "public/app/plugins/datasource/influxdb/img/influxdb_logo.svg"
    "access": "proxy"
    "url": "http://localhost:8086"
    "password": "INFLUXDB_PASSWORD"
    "user": "admin"
    "database": "saarctf"
    "basicAuth": false
    "isDefault": false
    "jsonData": {}
    "readOnly": false
