{
 "title": "Team Traffic",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "src",
    "label": "Origin (source)",
    "query": "SHOW TAG VALUES FROM \"traffic\" WITH KEY = \"src\""
   },
   {
    "name": "dst",
    "label": "Destination",
    "query": "SHOW TAG VALUES FROM \"traffic\" WITH KEY = \"dst\""
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": "SHOW TAG VALUES FROM \"traffic\" WITH KEY = \"proto\""
   },
   {
    "name": "port",
    "label": "Port",
    "query": "SHOW TAG VALUES FROM \"traffic\" WITH KEY = \"port\""
   }
  ]
 },
 "panels": [
  {
   "title": "Network Throughput",
   "type": "graph",
   "description": "Network troughput, stacked.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "query": "SELECT sum(\"src_bytes\") * 1000 / $__interval_ms AS \"request traffic\", sum(\"dst_bytes\") * 1000 / $__interval_ms AS \"response traffic\"\nFROM \"traffic\" WHERE (\"src\" =~ /^$src$/) AND (\"dst\" =~ /^$dst$/) AND (\"proto\" =~ /^$proto$/) AND (\"port\" =~ /^$port$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "src_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "dst_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic per Port (last 15min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_proto:$tag_port",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "proto" ], "type": "tag" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "query": "SELECT (sum(\"src_bytes\") + sum(\"dst_bytes\")) / 900 \nFROM \"traffic\" WHERE (\"src\" =~ /^$src$/) AND (\"dst\" =~ /^$dst$/) AND (\"proto\" =~ /^$proto$/) AND (\"port\" =~ /^$port$/) AND $timeFilter GROUP BY time(15m), \"proto\", \"port\" fill(null)",
     "select": [
      [
       { "params": [ "src_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth per Origin Team",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_src",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "src" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "query": "SELECT (sum(\"src_bytes\") + sum(\"dst_bytes\")) * 1000 / $__interval_ms \nFROM \"traffic\" WHERE (\"src\" =~ /^$src$/) AND (\"dst\" =~ /^$dst$/) AND (\"proto\" =~ /^$proto$/) AND (\"port\" =~ /^$port$/) AND $timeFilter GROUP BY time($__interval), \"src\" fill(null)",
     "select": [
      [
       { "params": [ "src_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth per Destination Team",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_dst",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "src" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "query": "SELECT (sum(\"src_bytes\") + sum(\"dst_bytes\")) * 1000 / $__interval_ms \nFROM \"traffic\" WHERE (\"src\" =~ /^$src$/) AND (\"dst\" =~ /^$dst$/) AND (\"proto\" =~ /^$proto$/) AND (\"port\" =~ /^$port$/) AND $timeFilter GROUP BY time($__interval), \"dst\" fill(null)",
     "select": [
      [
       { "params": [ "src_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "# connections" }
   ],
   "targets": [
    {
     "alias": "concurrent open connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "select": [
      [
       { "params": [ "open_connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dst", "operator": "=~", "value": "/^$dst$/" },
      { "condition": "AND", "key": "proto", "operator": "=~", "value": "/^$proto$/" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$port$/" }
     ]
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "alias": "new connections per second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"connection_count\")*1000/$__interval_ms AS \"connection count\" \nFROM \"traffic\" WHERE (\"src\" =~ /^$src$/) AND (\"dst\" =~ /^$dst$/) AND (\"proto\" =~ /^$proto$/) AND (\"port\" =~ /^$port$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connection Timing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "query": "SELECT sum(\"connection_times\")/sum(\"connection_count\") AS \"average connection time\"\nFROM \"traffic\" WHERE (\"src\" =~ /^$src$/) AND (\"dst\" =~ /^$dst$/) AND (\"proto\" =~ /^$proto$/) AND (\"port\" =~ /^$port$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "connection_times" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}